### ISSUE TITLE
Pesquisa de usuários e autores

### ISSUE THREAD

**Issue by SkiaBr23** [maximillianfx/BooksBlank#17]

**Comment by SkiaBr23** [comment]
@maximillianfx, a busca por autores é feita com a query de busca de livros "inauthor:query". Sugiro mudar a de livros pra "intitle:query" também.

Sobre a pesquisa de usuários, implementei uma função na PesquisaFragment (BuscarUsuarios) que recebe uma query de um nome e busca usuarios que tem essa substring no nome. Por motivos do firebase essa função popula uma lista global "users", resetada e repopulada a cada busca. Mas acredito que seja suficiente adicionar um "atualizaUsersView" no fim da query pra atualizar a tela de busca. A gente conversa.

**Comment by maximillianfx** [comment]
OK, essa de user é a última que vo configurar.

**Comment by maximillianfx** [comment]
Pesquisas implementadas.
